#!/bin/bash
# Test: extract summary from a plan with a well-formed implementation summary
cat <<'PLAN' > plan.md
# Implementation Plan: Test Plan

**Source ADRs:**
- [ADR-0099: Test decision](docs/adr/0099-test-decision.md)

**Generated:** 2026-01-15

---

## Summary

| Stage | Task | Cost | Dependencies |
|-------|------|------|--------------|
| 1. Setup | 1.1 Create config | small | — |
| 1. Setup | 1.2 Add validation | small | 1.1 |
| 2. Core | 2.1 Implement parser | medium | Stage 1 |

**Total estimated cost:** 2 small, 1 medium

<!-- Implementation summary generated by implement-adr -->

<!-- BEGIN implementation-summary -->
# task_id | status | cost | commit | description
1.1 | done | small | abc1234 | Create config file
1.2 | done | small | def5678 | Add validation logic
2.1 | done | medium | 9ab0123 | Implement parser module
3.1 | done | small | cde4567 | Update ADR status to Accepted
<!-- END implementation-summary -->
PLAN
awk -f "$SCRIPT_DIR/extract-summary.awk" plan.md
