#!/bin/bash
set -e

## usage: madr help [COMMAND]
##
## Shows help for madr commands.

bindir=$(cd -L $(dirname $0) >/dev/null 2>&1 && pwd -L)

if [ -z "$1" ]; then
    echo "usage: madr COMMAND [ARG] ..."
    echo "COMMAND is one of:"
    for f in "$bindir"/madr-*; do
        cmd=$(basename "$f" | sed 's/madr-/  /')
        echo "  $cmd"
    done
    echo ""
    echo "Run 'madr help COMMAND' for help on a specific command."
else
    sed -n 's/^## //p' "$bindir/madr-$1"
fi
