SKILL_ROOT := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

.PHONY: help

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'
